# Generated by Django 3.2.8 on 2021-10-22 18:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_add_sports_field'),
        ('sport_density', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigHexIntersections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('facilities', models.ManyToManyField(related_name='big_hexes', to='facilities.Facility')),
            ],
            options={
                'db_table': 'sport_density_big_hex_intersections',
            },
        ),
    ]
