# Generated by Django 3.2.8 on 2021-10-23 12:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_add_sports_field'),
        ('sport_density', '0002_bighexintersections'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHexBig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('flats', models.PositiveIntegerField()),
                ('facilities', models.ManyToManyField(related_name='big_hexes', to='facilities.Facility')),
            ],
            options={
                'db_table': 'sport_density_data_hex_big',
            },
        ),
        migrations.CreateModel(
            name='DataHexSmall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('flats', models.PositiveIntegerField()),
                ('facilities', models.ManyToManyField(related_name='hexes', to='facilities.Facility')),
            ],
            options={
                'db_table': 'sport_density_data_hex_small',
            },
        ),
        migrations.RemoveField(
            model_name='hexintersections',
            name='facilities',
        ),
        migrations.DeleteModel(
            name='BigHexIntersections',
        ),
        migrations.DeleteModel(
            name='HexIntersections',
        ),
    ]
