# Generated by Django 3.2.8 on 2021-10-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_density', '0003_change_intersections_to_data_hex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datahexbig',
            old_name='flats',
            new_name='population',
        ),
        migrations.RenameField(
            model_name='datahexsmall',
            old_name='flats',
            new_name='population',
        ),
    ]
