# Generated by Django 3.2.8 on 2021-11-05 13:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_density', '0004_change_flats_to_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquareColorBins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_id', models.PositiveIntegerField(null=True)),
                ('availability', models.PositiveIntegerField(null=True)),
                ('is_big_hexes', models.BooleanField(default=True)),
                ('bins', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=20)),
            ],
            options={
                'db_table': 'sport_density_square_color_bins',
            },
        ),
        migrations.CreateModel(
            name='SquarePerPersonColorBins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_id', models.PositiveIntegerField(null=True)),
                ('availability', models.PositiveIntegerField(null=True)),
                ('is_big_hexes', models.BooleanField(default=True)),
                ('bins', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=20)),
            ],
            options={
                'db_table': 'sport_density_square_per_person_color_bins',
            },
        ),
    ]
