# Generated by Django 3.2.8 on 2021-11-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_density', '0005_add_color_bins'),
    ]

    operations = [
        migrations.AddField(
            model_name='squarecolorbins',
            name='area_type',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='squareperpersoncolorbins',
            name='area_type',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
