# Generated by Django 3.2.8 on 2021-10-12 18:12

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('availability', models.PositiveSmallIntegerField(choices=[(1, 'City'), (2, 'Area'), (3, 'District'), (4, 'Step Availability')])),
                ('placement', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.department')),
            ],
        ),
        migrations.CreateModel(
            name='SportsAreaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'facilities_sports_area_type',
            },
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'facilities_sport_type',
            },
        ),
        migrations.CreateModel(
            name='SportsArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('sports', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.sportsareatype')),
            ],
            options={
                'db_table': 'facilities_sports_area',
            },
        ),
    ]
