# Generated by Django 3.2.8 on 2021-10-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsarea',
            name='square',
            field=models.FloatField(null=True),
        ),
    ]
