# Generated by Django 3.2.8 on 2021-10-17 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_sportsarea_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsarea',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='facilities.facility'),
        ),
    ]
