# Generated by Django 3.2.8 on 2021-10-18 18:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_rename_sports_area_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='sports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=[], size=70),
            preserve_default=False,
        ),
    ]
